permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments
#kramdown:
#  input: GFM

# 作者信息
author:
  name: 董朝
  email: yishuiliunian@gmail.com
  link: http://dzpqzb.com
  weibo: http://weibo.com/yishuiliunian
  github: http://github.com/yishuiliunian

# 站点信息
title: 一水的技术博客
description: iOS开发者，讲述一些关于OC、iOS、设计模式和架构的故事。欢迎关注微信公共账号IOS_Tips
url: http://dzpqzb.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://ww4.sinaimg.cn/large/7df22103jw1exx11uhhkoj20by0by3zc.jpg
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-33738381-1
  url: dzpqzb.com

# disqus 设置
disqus:
  shortname: yishuiliunian

comments: true
