permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments
#kramdown:
#  input: GFM

# 作者信息
author:
  name: 董朝
  email: yishuiliunian@gmail.com
  link: http://dzpqzb.com
  weibo: http://weibo.com/yishuiliunian
  github: http://github.com/yishuiliunian

# 站点信息
title: 一水的技术博客
description: 一水的技术博客
url: http://dzpqzb.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: yishuiliunian
